"""The R-compatible smoothing route, checked against R itself.

A Python port of a published R pipeline is only worth having if it gives the
published numbers. So this compares against reference output generated by the
original R code on 40 real PRISMA spectra, stored in
``tests/data/r_reference/prisma_smoothing.npz``. R is not needed to run these:
its answers are checked in.

The reference was produced by ``stats::smooth.spline`` and
``pracma::findpeaks``, driven by the same four-step core as the user's
``smooth_PRISMA_imagery.R``.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest
import xarray as xr

import hyperproc as hp
from hyperproc.spectral._smoothspline import nknots_smspl, smooth_spline
from hyperproc.spectral.smoothing import PRISMA_ARTEFACT_RANGES, PRISMA_MASK_AFTER, find_spikes

REF = Path(__file__).resolve().parent / "data" / "r_reference" / "prisma_smoothing.npz"


@pytest.fixture(scope="module")
def ref():
    if not REF.is_file():
        pytest.skip(f"no R reference at {REF}")
    return np.load(REF)


def _masked_input(ref, i):
    """One spectrum after steps 1 and 2, using R's own spike mask."""
    wl, spec = ref["wl"], ref["spectra"]
    s = spec[i].copy()
    s[ref["r_spikes"][i]] = np.nan
    drop = np.zeros(wl.size, bool)
    for lo, hi in PRISMA_ARTEFACT_RANGES:
        drop |= (wl >= lo) & (wl <= hi)
    s[drop] = np.nan
    return wl, s


# --------------------------------------------------------------------------- #
# step 1: the peak finder                                                      #
# --------------------------------------------------------------------------- #

def test_find_spikes_is_identical_to_pracma(ref):
    """Bit-for-bit, on every spectrum: this step is pure index logic."""
    got = np.array([find_spikes(s, 0.018) for s in ref["spectra"]])
    assert got.shape == ref["r_spikes"].shape
    assert np.array_equal(got, ref["r_spikes"])
    assert got.sum() > 0


def test_find_spikes_marks_three_bands_per_peak():
    """The peak, where its rise began and where its fall ended. Not the span."""
    x = np.array([0.10, 0.11, 0.12, 0.13, 0.50, 0.14, 0.15, 0.16, 0.155, 0.17, 0.40, 0.18, 0.19])
    assert np.array_equal(np.flatnonzero(find_spikes(x, 0.018)), [0, 4, 5, 8, 10, 11])


def test_find_spikes_respects_the_threshold():
    x = np.array([0.10, 0.11, 0.12, 0.13, 0.50, 0.14, 0.15, 0.16, 0.155, 0.17, 0.40, 0.18, 0.19])
    assert find_spikes(x, 0.018).sum() == 6            # two peaks qualify
    assert find_spikes(x, 1.0).sum() == 0              # none do
    assert find_spikes(x, 0.004).sum() > 6             # the small bump joins in


def test_find_spikes_finds_maxima_only():
    """Downward spikes survive step 1; the header comment says otherwise."""
    dip = np.array([0.3, 0.3, 0.3, 0.05, 0.3, 0.3, 0.3])
    assert not find_spikes(dip, 0.018).any()


def test_find_spikes_on_a_flat_spectrum_is_empty():
    assert not find_spikes(np.linspace(0.1, 0.2, 20), 0.018).any()


# --------------------------------------------------------------------------- #
# step 3: the spline                                                           #
# --------------------------------------------------------------------------- #

@pytest.mark.parametrize("n,expected", [(148, 78), (149, 79), (146, 77), (144, 77), (49, 49)])
def test_nknots_matches_r(n, expected):
    assert nknots_smspl(n) == expected


def test_spline_parameters_match_r(ref):
    """ratio, spar, lambda and df, against R's own reported values."""
    for i in range(ref["spectra"].shape[0]):
        wl, s = _masked_input(ref, i)
        ok = np.isfinite(s)
        fit = smooth_spline(wl[ok], s[ok], df=60)
        assert fit.ratio == pytest.approx(ref["r_ratio"][i], rel=1e-12)
        assert fit.spar == pytest.approx(ref["r_spar"][i], rel=1e-8)
        assert fit.lambda_ == pytest.approx(ref["r_lambda"][i], rel=1e-8)
        assert fit.df == pytest.approx(ref["r_df"][i], rel=1e-8)


def test_spline_at_a_fixed_lambda_matches_r(ref):
    """With the search removed, only the basis and penalty are under test.

    The tolerance is set by floating point, not by the port. R and numpy reach
    LAPACK by different routes, and the fit solves a dense system the size of
    the knot count, so the last couple of digits cannot agree bit for bit.
    Measured on the checked-in reference: median 9e-14, worst band 1.5e-12.
    A failure here means a real change in the basis or the penalty, not drift.
    """
    wl, s = _masked_input(ref, 0)
    ok = np.isfinite(s)
    fit = smooth_spline(wl[ok], s[ok], lam=1e-8)
    assert np.allclose(fit.predict(wl), ref["r_fixed_lambda"], atol=1e-11, rtol=0)
    assert fit.df == pytest.approx(68.5775091301, abs=1e-7)


def test_the_penalty_uses_r_s_constant():
    """R's sgram.f writes the integral of t^2 as 0.3330, not 1/3.

    It looks like a harmless rounding and is not: it shifts the penalty by 1e-3
    relative, which moves lambda and the fitted spectrum. Integrating exactly
    would be more correct and would not reproduce R.
    """
    from hyperproc.spectral._smoothspline import _gram, _knot_vector
    knot = _knot_vector(np.linspace(0, 1, 60), nknots_smspl(60))
    sigma = _gram(knot)
    assert np.allclose(sigma, sigma.T)
    assert np.all(np.diag(sigma) > 0)
    # an exact integral would differ in the fourth digit
    from scipy.interpolate import BSpline
    nk = knot.size - 4
    nodes, weights = np.polynomial.legendre.leggauss(3)
    edges = np.unique(knot)
    half, mid = (edges[1:] - edges[:-1]) / 2, (edges[1:] + edges[:-1]) / 2
    pts = (mid[:, None] + half[:, None] * nodes[None, :]).ravel()
    wts = (half[:, None] * weights[None, :]).ravel()
    d2 = np.column_stack([np.nan_to_num(
        BSpline(knot, np.eye(nk)[j], 3, extrapolate=False).derivative(2)(pts), nan=0.0)
        for j in range(nk)])
    exact = (d2 * wts[:, None]).T @ d2
    rel = abs(np.trace(sigma) - np.trace(exact)) / np.trace(exact)
    assert 1e-4 < rel < 1e-2, f"expected R's 0.3330 to differ from exact by ~1e-3, got {rel:.2e}"


def test_spline_recovers_a_smooth_function():
    """More degrees of freedom follow the curve more closely, as they must."""
    x = np.linspace(400, 2400, 300)
    y = 0.2 + 0.1 * np.sin(x / 300.0)
    errors = [np.abs(smooth_spline(x, y, df=d).predict(x) - y).max() for d in (20, 60, 150)]
    assert errors[0] > errors[1] > errors[2]
    assert errors[-1] < 1e-5


def test_spline_argument_checks():
    x, y = np.linspace(0, 1, 40), np.random.default_rng(0).normal(size=40)
    with pytest.raises(ValueError, match="one of df"):
        smooth_spline(x, y)
    with pytest.raises(ValueError, match="invalid df"):
        smooth_spline(x, y, df=1.0)
    # all-identical x gives IQR 0, so R's tol = 1e-6 * IQR(x) is rejected first
    with pytest.raises(ValueError, match="tol"):
        smooth_spline(np.zeros(10), np.zeros(10), df=3)
    # four distinct values, most of them duplicated, leaves too few unique points
    with pytest.raises(ValueError, match="four unique"):
        smooth_spline(np.array([0.0, 0, 0, 1, 1, 1, 2, 2, 2]), np.arange(9.0), df=3)


# --------------------------------------------------------------------------- #
# the whole pipeline                                                           #
# --------------------------------------------------------------------------- #

def _cube(ref):
    wl, spec = ref["wl"], ref["spectra"]
    return xr.Dataset(
        {"reflectance": (("y", "x", "wavelength"),
                         spec.reshape(spec.shape[0], 1, -1).astype("float32"))},
        coords={"wavelength": wl, "y": np.arange(spec.shape[0]), "x": [0]},
        attrs={"sensor": "PRISMA", "stem": "ref"})


def test_pipeline_matches_r(ref):
    out = hp.spline_gapfill(_cube(ref), df=60)
    got = out.reflectance.values.reshape(ref["spectra"].shape[0], -1)
    want = ref["r_smoothed"]
    assert np.array_equal(np.isfinite(got), np.isfinite(want)), "the NaN pattern differs"
    both = np.isfinite(got)
    assert np.abs(got[both] - want[both]).max() < 1e-6


def test_pipeline_masks_exactly_the_published_ranges(ref):
    out = hp.spline_gapfill(_cube(ref), df=60)
    wl = ref["wl"]
    after = np.zeros(wl.size, bool)
    for lo, hi in PRISMA_MASK_AFTER:
        after |= (wl >= lo) & (wl <= hi)
    values = out.reflectance.values.reshape(ref["spectra"].shape[0], -1)
    assert np.isnan(values[:, after]).all()
    assert np.isfinite(values[:, ~after]).all()


def test_pipeline_flags_which_bands_are_spline_fill(ref):
    """The R version does not record this; a reported value may be interpolated."""
    out = hp.spline_gapfill(_cube(ref), df=60)
    assert "spline_filled" in out
    filled = out["spline_filled"].values.reshape(ref["spectra"].shape[0], -1)
    values = out.reflectance.values.reshape(ref["spectra"].shape[0], -1)
    assert filled.any(), "some reported bands are interpolated"
    assert np.isfinite(values[filled]).all(), "a flagged band still carries a value"
    assert not filled[:, ref["wl"] < 500].any()


def test_pipeline_is_lazy_and_keeps_shape(ref):
    ds = _cube(ref).chunk({"y": 8})
    out = hp.spline_gapfill(ds, df=60)
    assert out["reflectance"].chunks is not None
    assert out.sizes == ds.sizes


def test_pipeline_rejects_an_impossible_df(ref):
    with pytest.raises(ValueError, match="df must satisfy"):
        hp.spline_gapfill(_cube(ref), df=1.0)


def test_smooth_spectra_is_untouched_by_all_this(ref):
    """The other smoother keeps its contract: it never fills a gap."""
    ds = _cube(ref)
    out = hp.smooth_spectra(ds, window=5)
    assert np.array_equal(np.isfinite(out.reflectance.values),
                          np.isfinite(ds.reflectance.values))
